### ISSUE TITLE
Permission denied alert.provisioning:read

### ISSUE THREAD

**Issue by YoonSungHyun-inzent** [VolkovLabs/volkovlabs-grapi-datasource#34] opened 2023-04-17 05:09 UTC
Hello,

I watched the YouTube video well.

An error occurred while proceeding according to the installation guide, so please inquire.

![image](https://user-images.githubusercontent.com/95339676/232383461-23bae83e-1f9c-4cfa-9edf-28a0d168ff2a.png)

I'm using grafana 9.4.7 version

and installed the app through Grafana plugins.

grafana log ::

logger=context userId=3 orgId=1 uname=sa-anotations t=2023-04-17T14:07:00.12210861+09:00 level=info msg="Access denied" userID=3 accessErrorID=ACE3144968927 permissions="action:alert.provisioning:read scopes:"
logger=context userId=3 orgId=1 uname=sa-anotations t=2023-04-17T14:07:00.122516508+09:00 level=info msg="Request Completed" method=GET path=/api/v1/provisioning/alert-rules status=403 remote_addr=[hide] time_ms=90 duration=90.233508ms size=173 referer= handler=/api/v1/provisioning/alert-rules

grafana ini

[unified_alerting]
enabled = true

**Comment by mikhail-vl** [comment] 2023-04-17 21:04
@YoonSungHyun-inzent Are you using Viewer permissions? You need Editor or Admin permissions to access provisioning.

  Let me know if there is anything else.

**Comment by mikhail-vl** [comment] 2023-04-17 21:08
We explained it in the documentation and Daria mentioned it in the latest step-by-step tutorial: https://volkovlabs.io/plugins/volkovlabs-grapi-datasource/configuration/.

**Comment by YoonSungHyun-inzent** [comment] 2023-04-18 00:06
@mikhail-vl permissions? Are you asking for the permissions of the dashboard?

![image](https://user-images.githubusercontent.com/95339676/232636153-aa9d44a6-30f9-495e-b54c-ee95b376bc64.png)

I'm going on with an admin account.

If you're talking about other permissions, can you let me know?

**Comment by mikhail-vl** [comment] 2023-04-18 00:16
@YoonSungHyun-inzent I was referencing the Token or API Key used for the Grafana HTTP API Data Source.

  The data source works with the provided credentials and not your user: https://volkovlabs.io/plugins/volkovlabs-grapi-datasource/configuration/.
  Let me know if it's clear.

**Comment by YoonSungHyun-inzent** [comment] 2023-04-18 00:21
@mikhail-vl 

You were talking about that authority.

![image](https://user-images.githubusercontent.com/95339676/232637623-31d75ac3-f1f3-452d-98df-bce060485f97.png)

![image](https://user-images.githubusercontent.com/95339676/232637610-dd6e110f-2a37-4191-b749-3ad45c86ea4e.png)

I added the token to the editor permission as shown above and added it to the datasource.

**Comment by YoonSungHyun-inzent** [comment] 2023-04-18 00:39
@mikhail-vl 

Can the remote Grafana URL from DataSource cause the above permission error?
Registering with localhost:3000 causes a bad gateway.

**Comment by mikhail-vl** [comment] 2023-04-18 01:06
@YoonSungHyun-inzent The data source is still very new. I need to experiment with different security levels.

  If you set the role as Admin to your Service Account, then it should work. It's probably related to your dashboard or configuration, which is Admin only.

**Comment by mikhail-vl** [comment] 2023-05-04 16:19
@YoonSungHyun-inzent The issue is resolved in https://github.com/VolkovLabs/volkovlabs-grapi-datasource/pull/39.

  Alert Rules required Admin permissions to return Alert Names and UIDs. We added an Exception Handling. You can test using the latest CI artifact before the official release: https://github.com/VolkovLabs/volkovlabs-grapi-datasource/actions/workflows/ci.yml

**Closed by mikhail-vl** 2023-05-04 16:19 UTC
Labels: question
